"""efgpp.lock.yaml - generated, never hand-maintained."""

from __future__ import annotations

import importlib.metadata as md
import platform
from pathlib import Path
from typing import Any

import yaml

from efgpp import __version__
from efgpp.data.registry import Registry, utcnow
from efgpp.project import LOCK_FILE, Project
from efgpp.resources.checksums import checksum_paths
from efgpp.setup.tools import ENV_NAMES

PYTHON_PACKAGES = ("pydantic", "typer", "rich", "pyyaml", "polars", "pyarrow", "duckdb", "pandera", "numpy",
                   "scipy", "anndata", "mudata", "zarr", "plotly", "jinja2", "httpx", "filelock", "blake3",
                   "phenopackets", "ga4gh.vrs", "alphagenome")


def _env_hash(project: Project, name: str) -> dict[str, Any] | None:
    d = project.envs_dir / name
    files = [p for p in (d / "pixi.toml", d / "pixi.lock", project.path("workflow", "envs", f"{name}.yaml")) if p.exists()]
    installed = (d / ".pixi").exists() or (d / "conda-meta").exists()
    if not files:
        return None
    return {"installed": installed, "manager": "pixi" if (d / "pixi.toml").exists() else "conda-family (workflow/envs spec)",
            "sha256": str(checksum_paths(files).value), "files": [p.name for p in files]}


def _source_pins(project: Project) -> dict[str, Any]:
    """Pinned source installs (software/opt/<name>/EFGPP_SOURCE.json): repository, commit, archive SHA-256."""
    import json

    out: dict[str, Any] = {}
    for d in (project.software_dir, *project.legacy_software_dirs):
        for pin in sorted((d / "opt").glob("*/EFGPP_SOURCE.json")) if (d / "opt").exists() else []:
            try:
                out[pin.parent.name] = json.loads(pin.read_text(encoding="utf-8"))
            except ValueError:
                continue
    return out


def write_lock(project: Project, containers: dict[str, str | None] | None = None) -> Path:
    packages = {}
    for pkg in PYTHON_PACKAGES:
        try:
            packages[pkg] = md.version(pkg)
        except md.PackageNotFoundError:
            continue
    with Registry.open(project) as reg:
        software = reg.rows("SELECT name, environment, version, path FROM software ORDER BY name, environment")
        resources = reg.rows("SELECT name, version, genome_build, checksum, source, metadata FROM resources ORDER BY name, version")
    lock = {
        "lock_version": 1,
        "efgpp_version": __version__,
        "generated_at": utcnow().isoformat(timespec="seconds") + "Z",
        "platform": {"system": platform.system(), "machine": platform.machine(), "python": platform.python_version()},
        "python_packages": packages,
        "software": software,
        "environments": {n: h for n in ENV_NAMES if (h := _env_hash(project, n))},
        "containers": containers or {},
        "sources": _source_pins(project),
        "resources": [
            {k: v for k, v in r.items() if k != "metadata"}
            | {"download_sha256": (r.get("metadata") or {}).get("download_sha256")}
            for r in resources
        ],
        "configuration": project.config_checksums(),
    }
    path = project.path(LOCK_FILE)
    header = "# Generated by EFGPP. Do not edit by hand; regenerate with `efgpp setup data` or `efgpp data prepare`.\n"
    path.write_text(header + yaml.safe_dump(lock, sort_keys=False, default_flow_style=False), encoding="utf-8")
    return path
