"""`efgpp export slurm`: explicit, human-readable SLURM batch scripts for the data plan."""

from __future__ import annotations

import os
import stat
from collections import defaultdict
from pathlib import Path

from efgpp.data.plan import Step, build_plan
from efgpp.project import Project
from efgpp.workflow.snakemake import step_command

GROUP_ORDER = ["prepare", "genotype_qc", "pca", "relatedness", "annotation", "expression_prediction", "report"]


def _group_dependencies(steps: list[Step]) -> dict[str, set[str]]:
    group_of = {s.id: s.group for s in steps}
    deps: dict[str, set[str]] = defaultdict(set)
    for s in steps:
        for n in s.needs:
            g = group_of.get(n)
            if g and g != s.group:
                deps[s.group].add(g)
    return deps


def export_slurm(project: Project, out_dir: Path | None = None) -> list[Path]:
    hpc = project.config.execution.hpc
    out_dir = out_dir or project.path("hpc")
    out_dir.mkdir(parents=True, exist_ok=True)
    steps = [s for s in build_plan(project) if s.enabled]
    groups: dict[str, list[Step]] = defaultdict(list)
    for s in steps:
        groups[s.group].append(s)
    order = [g for g in GROUP_ORDER if g in groups] + sorted(set(groups) - set(GROUP_ORDER))
    written: list[Path] = []
    for group in order:
        members = groups[group]
        threads = max(s.threads for s in members)
        mem = max(s.mem_mb for s in members)
        minutes = sum(s.runtime_min for s in members)
        header = [
            "#!/bin/bash",
            f"#SBATCH --job-name=efgpp_{group}",
            f"#SBATCH --cpus-per-task={threads}",
            f"#SBATCH --mem={mem}M",
            f"#SBATCH --time={minutes // 60:02d}:{minutes % 60:02d}:00",
            f"#SBATCH --output={project.root.as_posix()}/.efgpp/logs/slurm_{group}_%j.out",
        ]
        if hpc.partition:
            header.append(f"#SBATCH --partition={hpc.partition}")
        if hpc.account:
            header.append(f"#SBATCH --account={hpc.account}")
        body = ["", "set -euo pipefail", f'cd "{project.root.as_posix()}"', ""]
        for s in members:
            body.append(f"# {s.description}")
            body.append(step_command(project, s, threads="${SLURM_CPUS_PER_TASK:-1}"))
        path = out_dir / f"{group}.sbatch"
        path.write_text("\n".join(header + body) + "\n", encoding="utf-8", newline="\n")
        written.append(path)

    deps = _group_dependencies(steps)
    submit = ["#!/bin/bash", "# Submit EFGPP data jobs with dependencies. Generated by `efgpp export slurm`.",
              "set -euo pipefail", f'cd "{out_dir.as_posix()}"', ""]
    for group in order:
        after = [f"${{JOB_{d.upper()}}}" for d in order if d in deps.get(group, set())]
        dep = f"--dependency=afterok:{':'.join(after)} " if after else ""
        submit.append(f"JOB_{group.upper()}=$(sbatch --parsable {dep}{group}.sbatch)")
        submit.append(f'echo "{group}: $JOB_{group.upper()}"')
    script = out_dir / "submit_all.sh"
    script.write_text("\n".join(submit) + "\n", encoding="utf-8", newline="\n")
    for p in [*written, script]:
        os.chmod(p, os.stat(p).st_mode | stat.S_IXUSR)
    written.append(script)
    return written
