"""Snakefile generation from the data plan, and Snakemake invocation."""

from __future__ import annotations

import re
import shlex
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

from efgpp.data.plan import Step
from efgpp.project import Project
from efgpp.setup.tools import resolve

GROUP_FILES = {
    "prepare": "validate.smk",
    "genotype_qc": "genotype_qc.smk",
    "pca": "pca.smk",
    "relatedness": "relatedness.smk",
    "annotation": "annotation.smk",
    "expression_prediction": "predixcan.smk",
    "report": "report.smk",
}


def rule_name(step_id: str) -> str:
    return re.sub(r"\W", "_", step_id)


def step_command(project: Project, step: Step, threads: str = "{threads}") -> str:
    python = Path(sys.executable).as_posix()
    return (f'"{python}" -m efgpp --project "{project.root.as_posix()}" data step {shlex.quote(step.id)} '
            f"--threads {threads} --marker {step.marker}")


def render_rule(project: Project, step: Step, by_id: dict[str, Step]) -> str:
    inputs = []
    for need in step.needs:
        up = by_id.get(need)
        if up is None or not up.enabled:
            continue
        # Always-run upstream steps must not force downstream reruns by modification time.
        inputs.append(f'ancient("{up.marker}")' if up.always_run else f'"{up.marker}"')
    lines = [f"rule {rule_name(step.id)}:"]
    if inputs:
        lines.append("    input:")
        lines += [f"        {i}," for i in inputs]
    lines += [
        "    output:",
        f'        "{step.marker}",',
        f"    threads: {step.threads}",
        "    resources:",
        f"        mem_mb={step.mem_mb},",
        f"        runtime={step.runtime_min},",
        "    log:",
        f'        "logs/snakemake/{step.id}.log",',
        f"    message: {step.description!r}",
        "    shell:",
        f"        {(step_command(project, step) + ' > {log} 2>&1')!r}",
        "",
    ]
    return "\n".join(lines)


def write_snakefile(project: Project, steps: list[Step]) -> Path:
    wf = project.path("workflow")
    rules_dir = wf / "rules"
    rules_dir.mkdir(parents=True, exist_ok=True)
    for old in rules_dir.glob("*.smk"):
        old.unlink()
    enabled = [s for s in steps if s.enabled]
    by_id = {s.id: s for s in steps}
    grouped: dict[str, list[Step]] = defaultdict(list)
    for s in enabled:
        grouped[GROUP_FILES.get(s.group, f"{s.group}.smk")].append(s)
    for filename, group_steps in grouped.items():
        body = "# Generated by `efgpp data plan`; do not edit.\n\n" + "\n".join(
            render_rule(project, s, by_id) for s in group_steps)
        (rules_dir / filename).write_text(body, encoding="utf-8")
    targets = ",\n".join(f'        "{s.marker}"' for s in enabled)
    includes = "\n".join(f'include: "rules/{f}"' for f in sorted(grouped))
    snakefile = wf / "Snakefile"
    snakefile.write_text(
        "# Generated by `efgpp data plan`. EFGPP decides WHAT runs; Snakemake decides WHEN.\n"
        "# Each rule calls `efgpp data step <id>`, which runs its tools in their own environment.\n\n"
        f"rule all:\n    input:\n{targets},\n    default_target: True\n\n{includes}\n",
        encoding="utf-8",
    )
    return snakefile


def run_snakemake(project: Project, *, cores: int, executor: str | None = None, dry_run: bool = False,
                  extra: list[str] | None = None) -> int:
    tool = resolve(project, "snakemake")
    profile = project.path("workflow", "profiles", "slurm" if executor == "slurm" else "local")
    args = ["--snakefile", str(project.path("workflow", "Snakefile")), "--directory", str(project.root),
            "--profile", str(profile), "--cores", str(cores)]
    if executor and executor != "local":
        args += ["--executor", executor]
    if dry_run:
        args.append("--dry-run")
    proc = subprocess.run(tool.command(*args, *(extra or [])), cwd=project.root, env=tool.environ())
    return proc.returncode
