"""Scientific environment definitions and Snakemake profiles written at `efgpp init`.

One small environment per purpose - never one enormous environment.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import yaml

if TYPE_CHECKING:
    from efgpp.project import Project

CHANNELS = ["conda-forge", "bioconda"]

# Conda/Bioconda package specifications per environment.
ENVIRONMENTS: dict[str, dict[str, str]] = {
    "core": {"python": ">=3.11", "snakemake-minimal": ">=8", "snakemake-executor-plugin-slurm": "*"},
    "genetics": {"plink2": "*", "plink": "*", "bcftools": "*", "htslib": "*", "flashpca": "*"},
    "annotation": {"ensembl-vep": "*", "htslib": "*", "open-cravat": "*"},
    "metaxcan": {"python": "3.10.*", "numpy": "*", "scipy": "*", "pandas": "*", "cyvcf2": "*",
                 "bgen-reader": "*", "h5py": "*", "git": "*"},
    "reporting": {"multiqc": "*"},
}

# Packages without a build for a platform are dropped from that platform's manifest.
UNAVAILABLE = {
    "osx-arm64": {"flashpca", "plink"},
    "linux-aarch64": {"flashpca"},
}

LOCAL_PROFILE = {
    "cores": 8,
    "keep-going": True,
    "rerun-incomplete": True,
    "printshellcmds": True,
    "retries": 1,
}


def slurm_profile(project: Project) -> dict[str, object]:
    hpc = project.config.execution.hpc
    resources = [f"mem_mb={hpc.default_mem_mb}", f"runtime={hpc.default_runtime_min}"]
    if hpc.partition:
        resources.append(f"slurm_partition={hpc.partition}")
    if hpc.account:
        resources.append(f"slurm_account={hpc.account}")
    return {
        "executor": "slurm",
        "jobs": hpc.max_jobs,
        "default-resources": resources,
        "retries": 2,
        "latency-wait": 60,
        "keep-going": True,
        "rerun-incomplete": True,
        "printshellcmds": True,
    }


def conda_env_yaml(name: str) -> dict[str, object]:
    deps = [f"{pkg}{'' if ver == '*' else ver}" for pkg, ver in ENVIRONMENTS[name].items()]
    return {"name": f"efgpp-{name}", "channels": CHANNELS, "dependencies": deps}


def pixi_manifest(name: str, platform: str) -> str:
    skip = UNAVAILABLE.get(platform, set())
    lines = [
        "[workspace]",
        f'name = "efgpp-{name}"',
        f"channels = {CHANNELS!r}".replace("'", '"'),
        f'platforms = ["{platform}"]',
        "",
        "[dependencies]",
    ]
    lines += [f'{pkg} = "{ver}"' for pkg, ver in ENVIRONMENTS[name].items() if pkg not in skip]
    return "\n".join(lines) + "\n"


def write_workflow_templates(project: Project) -> None:
    wf = project.path("workflow")
    (wf / "envs").mkdir(parents=True, exist_ok=True)
    for name in ENVIRONMENTS:
        (wf / "envs" / f"{name}.yaml").write_text(
            yaml.safe_dump(conda_env_yaml(name), sort_keys=False), encoding="utf-8")
    for profile, content in (("local", LOCAL_PROFILE), ("slurm", slurm_profile(project))):
        d = wf / "profiles" / profile
        d.mkdir(parents=True, exist_ok=True)
        (d / "config.yaml").write_text(yaml.safe_dump(content, sort_keys=False), encoding="utf-8")
    snakefile = wf / "Snakefile"
    if not snakefile.exists():
        snakefile.write_text(
            "# Generated by `efgpp data plan`. EFGPP decides WHAT runs; Snakemake decides WHEN.\n"
            "# Run `efgpp data plan` to populate the rules for this project.\n",
            encoding="utf-8",
        )
